name: End-to-End (e2e) testing against fake backends

on:
  pull_request:
    branches:
      - main
    types: [ready_for_review]
  schedule:
    - cron: '0 0 * * *'

jobs:
  e2e_tests:
    if: |
      success() && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          uv pip install --constraint requirements.txt --editable .[mgst,examples]
      - name: Test if example notebooks run successfully
        working-directory: ./docs/examples
        run: jupyter execute example_clifford_rb.ipynb
